---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-template-kubevirt-io-v1alpha1-virtualmachinetemplate
  failurePolicy: Fail
  name: vvirtualmachinetemplate-v1alpha1.kb.io
  rules:
  - apiGroups:
    - template.kubevirt.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualmachinetemplates
  sideEffects: None
