---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apiserver-role
rules:
- apiGroups:
  - template.kubevirt.io
  resources:
  - virtualmachinetemplates
  - virtualmachinetemplates/status
  verbs:
  - get
