---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - template.kubevirt.io
  resources:
  - virtualmachinetemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - template.kubevirt.io
  resources:
  - virtualmachinetemplates/finalizers
  verbs:
  - update
- apiGroups:
  - template.kubevirt.io
  resources:
  - virtualmachinetemplates/status
  verbs:
  - get
  - patch
  - update
