# This rule is not used by the project virt-template itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over template.kubevirt.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: virt-template
    app.kubernetes.io/managed-by: kustomize
  name: virtualmachinetemplate-admin-role
rules:
- apiGroups:
  - template.kubevirt.io
  resources:
  - virtualmachinetemplates
  verbs:
  - '*'
- apiGroups:
  - template.kubevirt.io
  resources:
  - virtualmachinetemplates/status
  verbs:
  - get
