apiVersion: template.kubevirt.io/v1alpha1
kind: VirtualMachineTemplate
metadata:
  labels:
    app.kubernetes.io/name: virt-template
    app.kubernetes.io/managed-by: kustomize
  name: virtualmachinetemplate-sample
spec:
  # TODO(user): Add fields here
